{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keepiq-operator.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keepiq-operator.labels" . | nindent 4 }}
{{- end }}
