# SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
# SPDX-License-Identifier: EUPL-1.2
#
# R8 for the release build (build.gradle.kts). Debug and e2e builds are not
# shrunk. Most libraries ship their own rules in their jar or AAR, and R8
# reads those: kotlinx.serialization and kotlinx.coroutines
# (META-INF/com.android.tools), Ktor (META-INF/proguard/ktor.pro), SQLCipher
# (proguard.txt: its JNI classes and native methods), OkHttp, AndroidX and
# Compose. androidx.credentials, for the passkey work, ships its own too.
# What is left is below.

# Readable stack traces in bug reports from a free-software app: shrink and
# optimise, but keep the names. It also means no mapping file to keep per
# release, and the APK stays easy to compare with a build from source.
-dontobfuscate

# SQLCipher's JNI code calls back into these by name; its own rules keep the
# native methods, this keeps the classes the native side looks up.
-keep class net.zetetic.database.** { *; }

# The offline store's queries, generated by SQLDelight, are plain code; its
# Android driver needs nothing extra.

# kotlinx.serialization: the companion serializer of every @Serializable
# class in the app and the shared core (the library's rules cover the
# lookup; this keeps the classes Keepiq stores and sends intact).
-keepclassmembers @kotlinx.serialization.Serializable class nl.conduction.keepiq.** {
    *** Companion;
    *** INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}

# BouncyCastle is only used for Argon2 (Primitives.jvmShared.kt), through
# its lightweight API with direct references, so R8 keeps what is called.
# The provider classes refer to JDK parts Android does not have.
-dontwarn javax.naming.**
-dontwarn org.bouncycastle.jsse.**

# Ktor and coroutines refer to JVM-only classes in code paths Android never
# takes; OkHttp to TLS providers Keepiq does not ship.
-dontwarn java.lang.management.**
-dontwarn org.slf4j.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**
-dontwarn reactor.blockhound.**
