import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';
import autoImports from './.wxt/eslint-auto-imports.mjs';

export default [
	{
		ignores: ['.output/**', '.wxt/**', 'node_modules/**'],
	},
	js.configs.recommended,
	...tseslint.configs.recommended,
	// Teaches ESLint about WXT's auto-imported globals (`browser`,
	// `defineBackground`, …). Generated by `wxt prepare`, driven by
	// `imports.eslintrc` in wxt.config.ts.
	autoImports,
	{
		files: ['entrypoints/**/*.tsx'],
		...reactHooks.configs.flat.recommended,
	},
	{
		// User-facing text comes from locales/ (ext-i18n).
		files: ['entrypoints/**/*.tsx'],
		ignores: ['**/*.test.tsx'],
		rules: {
			'no-restricted-syntax': ['error',
				{ selector: 'JSXText[value=/[A-Za-z]/]', message: 'Put user-facing text in locales/ and use i18n.t().' },
				{ selector: 'JSXAttribute[name.name=/^(label|title|aria-label|placeholder|question|detail|action|text|alt)$/] > Literal[value=/[A-Za-z]/]', message: 'Put user-facing text in locales/ and use i18n.t().' },
			],
		},
	},
	{
		// Build tooling runs in Node, not in the extension — without this every
		// `process` / `console` reference is a `no-undef` error.
		files: ['scripts/**/*.{js,mjs,ts}'],
		languageOptions: {
			globals: globals.nodeBuiltin,
		},
	},
];
