/**
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 *
 * The verification phrase two devices show for one one-time public key
 * (crypto-new-device-approval D2, shared with organisation account
 * recovery): five words picked by the first five bytes of the SHA-256 of
 * the key. If anyone swapped the key on its way, the phrases differ.
 */

/**
 * 256 short, distinct, lower-case English words, one per byte value. The
 * list is fixed: changing it changes every phrase.
 */
export const PHRASE_WORDS = Object.freeze([
	'acid',
	'acorn',
	'actor',
	'adult',
	'agent',
	'alarm',
	'album',
	'alert',
	'alley',
	'amber',
	'angle',
	'ankle',
	'apple',
	'april',
	'apron',
	'arena',
	'arrow',
	'atlas',
	'attic',
	'audio',
	'award',
	'bacon',
	'badge',
	'bagel',
	'baker',
	'bamboo',
	'banjo',
	'barn',
	'basil',
	'beach',
	'beard',
	'bench',
	'berry',
	'bike',
	'bird',
	'blade',
	'blanket',
	'bloom',
	'board',
	'boat',
	'bolt',
	'bone',
	'book',
	'boot',
	'bottle',
	'bowl',
	'brain',
	'brass',
	'bread',
	'brick',
	'bridge',
	'broom',
	'brush',
	'bucket',
	'bunny',
	'cabin',
	'cable',
	'cactus',
	'cake',
	'camel',
	'camera',
	'candle',
	'canoe',
	'canyon',
	'carbon',
	'cargo',
	'carpet',
	'carrot',
	'castle',
	'cedar',
	'chair',
	'chalk',
	'cheese',
	'cherry',
	'chess',
	'chief',
	'chimney',
	'cider',
	'circle',
	'clam',
	'cliff',
	'clock',
	'cloud',
	'clover',
	'coach',
	'cobra',
	'cocoa',
	'coffee',
	'comet',
	'copper',
	'coral',
	'cotton',
	'couch',
	'crab',
	'crane',
	'crayon',
	'cream',
	'cricket',
	'crown',
	'cube',
	'cup',
	'daisy',
	'dawn',
	'deer',
	'delta',
	'desert',
	'diamond',
	'dinner',
	'dolphin',
	'donkey',
	'door',
	'dragon',
	'drum',
	'duck',
	'eagle',
	'earth',
	'easel',
	'echo',
	'eel',
	'elbow',
	'elm',
	'ember',
	'engine',
	'falcon',
	'feather',
	'fence',
	'fern',
	'ferry',
	'fiddle',
	'field',
	'flag',
	'flame',
	'flute',
	'forest',
	'fossil',
	'fox',
	'frog',
	'garden',
	'garlic',
	'gate',
	'gecko',
	'ginger',
	'glacier',
	'globe',
	'glove',
	'goat',
	'grape',
	'gravel',
	'guitar',
	'hammer',
	'harbor',
	'harp',
	'hazel',
	'helmet',
	'heron',
	'honey',
	'hornet',
	'horse',
	'igloo',
	'island',
	'ivory',
	'jacket',
	'jaguar',
	'jelly',
	'jungle',
	'kayak',
	'kettle',
	'kiwi',
	'koala',
	'ladder',
	'lake',
	'lamp',
	'lantern',
	'lemon',
	'lily',
	'lion',
	'lizard',
	'lobster',
	'locket',
	'lotus',
	'magnet',
	'mango',
	'maple',
	'marble',
	'meadow',
	'melon',
	'mirror',
	'mitten',
	'moose',
	'motor',
	'mountain',
	'mouse',
	'muffin',
	'mule',
	'needle',
	'nest',
	'noodle',
	'oak',
	'oasis',
	'ocean',
	'olive',
	'onion',
	'orange',
	'orchid',
	'otter',
	'owl',
	'paddle',
	'panda',
	'paper',
	'parrot',
	'peach',
	'pebble',
	'pencil',
	'pepper',
	'piano',
	'pickle',
	'pigeon',
	'pillow',
	'pine',
	'planet',
	'plum',
	'pony',
	'poppy',
	'potato',
	'puffin',
	'pumpkin',
	'quartz',
	'rabbit',
	'radish',
	'raven',
	'reef',
	'ribbon',
	'river',
	'robin',
	'rocket',
	'rose',
	'saddle',
	'salmon',
	'sand',
	'scarf',
	'seal',
	'shell',
	'ship',
	'silver',
	'sketch',
	'sled',
	'snail',
	'spider',
	'spoon',
	'spruce',
	'squid',
	'stamp',
	'star',
	'stone',
	'storm',
	'sugar',
])

/** How many words a phrase has. */
export const PHRASE_LENGTH = 5

/**
 * The verification phrase of a public key.
 *
 * @param {Uint8Array|ArrayBuffer} publicKeyRaw The raw public key bytes.
 * @return {Promise<string>} Five words separated by spaces.
 * @spec openspec/specs/new-device-approval/spec.md#requirement-both-devices-show-the-same-verification-phrase
 */
export async function verificationPhrase(publicKeyRaw) {
	const bytes =
		publicKeyRaw instanceof Uint8Array
			? publicKeyRaw
			: new Uint8Array(publicKeyRaw)
	const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))
	return Array.from(
		digest.slice(0, PHRASE_LENGTH),
		(byte) => PHRASE_WORDS[byte],
	).join(' ')
}

/**
 * The verification phrase of a base64-encoded public key.
 *
 * @param {string} publicKeyBase64 The raw public key, base64.
 * @return {Promise<string>}
 * @spec openspec/specs/new-device-approval/spec.md#requirement-both-devices-show-the-same-verification-phrase
 */
export async function verificationPhraseFromBase64(publicKeyBase64) {
	const binary = atob(publicKeyBase64)
	const bytes = new Uint8Array(binary.length)
	for (let i = 0; i < binary.length; i++) {
		bytes[i] = binary.charCodeAt(i)
	}
	return verificationPhrase(bytes)
}
